name: Java Service CI

on:
  push:
    branches:
      - EJ-26-java-docker-container-and-git-hub-hooks-implementation

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21


      - name: Build with Gradle
        run: ./gradlew clean build --stacktrace


      - name: Run tests
        run: ./gradlew test --stacktrace
      
